### ISSUE TITLE
[FEAT] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-accountbook-20#1]
## 개요
프로젝트에서 주로 사용되는 컴포넌트들에 대해 설정합니다.

## TODO
- [x] 프로젝트 의존성 implementation 하기
- [x] Hilt 의존성 추가 및 HiltApplication 설정
- [x] 색상, 폰트, 아이콘 등 상수 설정
