### ISSUE TITLE
[FEAT] MainActivity

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-accountbook-20#2]
## 개요
1. 메인 화면에 사용되는 뷰인 네비게이션 컴포넌트 초기 설정
2. 바텀 내비게이션 바를 생성해 연동
3. 전역적으로 사용되는 앱바 개발

## TODO
- [x] Compose용 Navigation Component의 의존성 추가
- [x] MainActivity에 Navigation Component 설정
- [x] 바텀 내비게이션 바 추가 및 ‘내역’ 기본값 설정
- [x] 뒤로가기 버튼이 존재하는 앱바
- [x] 날짜 이동 기능이 있는 앱바
