### ISSUE TITLE
[FEAT] HistoryScreen

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-accountbook-20#3]
## 개요
홈 화면의 수입/지출 내역 화면 개발

## TODO
- [x] Scaffold를 활용해 홈 화면의 앱바와 FAB 버튼 추가
- [x] 체크박스 컴포넌트 구현
- [x] LazyColumn으로 리스트 구현
- [x]  리스트 아이템 롱 클릭시 선택 모드 변경 및 삭제 버튼 보이기
- [x]  아이템이 0개일 시 선택 모드 종료
- [ ] SQLiteOpenHelper 연동
