### ISSUE TITLE
[FEAT] HistoryCreateScreen

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-accountbook-20#4]
## 개요
수입/지출 내역을 추가하는 화면 개발

## TODO
- [x] 라디오 컴포넌트 구현
- [x] 일자, 금액, 결제 수단이 비어있을 때 등록하기 버튼 비활성화
- [x] 분류가 비어있을 때 자동으로 미분류 설정
- [x] 드롭다운 메뉴 개발
- [x] 앱바 NavigationIcon 클릭 시 입력 값 삭제 및 뒤로가기
- [x] 등록하기 버튼 클릭 시 DB 값 저장하고 내역 목록으로 되돌아가 리스트 refresh
- [x] 기존의 아이템 수정 시 ‘등록하기’는’ 저장’으로 변하고 클릭 시 DB에서 값 업데이트
- [ ] SQLiteOpenHelper 연동
