### ISSUE TITLE
[FEAT] SettingScreen

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-accountbook-20#7]
## 개요
설정 화면입니다.

## TODO
- [x] 설정 전용 앱바 추가
- [ ] LazyColumn으로 리스트 구현
- [ ] 결제 수단 또는 지출 카테고리 추가 버튼 클릭 시 이동
