### ISSUE TITLE
[FEAT] CategoryCreateScreen

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-accountbook-20#8]
## 개요
지출 카테고리 추가 화면입니다.

## TODO
- [ ] 이름이 입력되지 않으면 등록하기 버튼이 비활성화
- [ ] 등록된 결제 수단을 클릭 시 수정화면 기능. 모든 ‘추가’ 글자가 ‘수정’으로 변화
- [ ] 시간 남으면 이름 검증
- [ ] 색상은 선택하지 않아도 기본값 적용
